name: Deploy Cloudflare Worker

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'false'

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Publish to Cloudflare Workers
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        run: |
          wrangler publish
